[package]
name = "cameron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.0"
regex = "1.10.3"
strum = "0.26.1"
strum_macros = "0.26.1"
